apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: advise-psp
spec:
  version: {{ .TagName }}
  homepage: https://github.com/sysdiglabs/kube-policy-advisor
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/sysdiglabs/kube-policy-advisor/releases/download/{{ .TagName }}/kube-policy-advisor_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-advise-psp
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/sysdiglabs/kube-policy-advisor/releases/download/{{ .TagName }}/kube-policy-advisor_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-advise-psp
  shortDescription: Suggests PodSecurityPolicies for cluster.
  description: |
    Suggests PSPs based on the required capabilities of the currently running
    workloads or a given manifest.
